# Generated by Django 3.2.17 on 2023-02-16 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('projects', '0001_initial'), ('projects', '0002_project_prefix'), ('projects', '0003_project_members'), ('projects', '0004_auto_20230204_1343'), ('projects', '0003_alter_project_prefix'), ('projects', '0005_merge_20230204_1541'), ('projects', '0006_alter_project_prefix'), ('projects', '0007_alter_project_options')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('Sandbox', 'Sandbox'), ('R&D', 'R&D'), ('Internal', 'Internal'), ('Public Product', 'Public Product'), ('Private Product', 'Private Product')], default='R&D', max_length=30)),
                ('prefix', models.CharField(blank=True, max_length=4, null=True)),
                ('members', models.ManyToManyField(blank=True, related_name='project_members', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
