# Generated by Django 3.2.16 on 2023-01-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='prefix',
            field=models.CharField(default='UA', max_length=4, unique=True),
        ),
    ]
