# Generated by Django 3.2.16 on 2023-01-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='prefix',
            field=models.CharField(default='UA', max_length=4),
        ),
    ]
