# Generated by Django 3.2.16 on 2023-02-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_prefix'),
        ('projects', '0004_auto_20230204_1343'),
    ]

    operations = [
    ]
