# Generated by Django 3.2.16 on 2023-01-29 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0003_alter_sprint_status'),
        ('tasks', '0003_task_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sprints.sprint'),
        ),
    ]
