# Generated by Django 3.2.16 on 2023-02-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blocking_tasks',
            field=models.ManyToManyField(blank=True, related_name='_tasks_task_blocking_tasks_+', to='tasks.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='related_to_tasks',
            field=models.ManyToManyField(blank=True, related_name='_tasks_task_related_to_tasks_+', to='tasks.Task'),
        ),
    ]
