# Generated by Django 3.2.17 on 2023-02-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
