# Generated by Django 3.2.17 on 2023-02-14 23:55

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_task_date_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
