# Generated by Django 3.2.17 on 2023-02-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_sprint'),
        ('tasks', '0019_category_project'),
    ]

    operations = [
    ]
