# Generated by Django 3.2.16 on 2023-01-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('Sandbox', 'Sandbox'), ('R&D', 'R&D'), ('Internal', 'Internal'), ('Public Product', 'Public Product'), ('Private Product', 'Private Product')], default='R&D', max_length=30)),
            ],
        ),
    ]
