# Generated by Django 3.2.16 on 2023-02-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_merge_20230204_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='prefix',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
