# Generated by Django 3.2.17 on 2023-02-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0004_sprint_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Ended', 'Ended'), ('Not Started', 'Not Started')], default='Open', max_length=20),
        ),
    ]
