# Generated by Django 3.2.16 on 2023-01-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blocked_by_tasks',
            field=models.ManyToManyField(blank=True, related_name='_tasks_task_blocked_by_tasks_+', to='tasks.Task'),
        ),
    ]
