# Generated by Django 3.2.16 on 2023-01-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cloned_by_tasks',
            field=models.ManyToManyField(blank=True, related_name='_tasks_task_cloned_by_tasks_+', to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Task', 'Task'), ('Feature', 'Feature'), ('Bug', 'Bug'), ('Story', 'Story'), ('Epic', 'Epic'), ('Spike', 'Spike')], default='Task', max_length=30),
        ),
    ]
