# Generated by Django 3.2.16 on 2023-01-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_comment_options'),
        ('tasks', '0007_auto_20230129_1425'),
    ]

    operations = [
    ]
