# Generated by Django 3.2.17 on 2023-02-06 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='effort',
            field=models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
