# Generated by Django 3.2.17 on 2023-02-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_task_effort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature'), ('Enhancement', 'Enhancement'), ('Epic', 'Epic'), ('Spike', 'Spike'), ('Story', 'Story'), ('Task', 'Task')], default='Task', max_length=30),
        ),
    ]
