# Generated by Django 3.2.17 on 2023-02-16 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    replaces = [('sprints', '0001_initial'), ('sprints', '0002_sprint_name'), ('sprints', '0003_alter_sprint_status'), ('sprints', '0004_sprint_description'), ('sprints', '0005_alter_sprint_status'), ('sprints', '0006_alter_sprint_status')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_project_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Ended', 'Ended'), ('Not Started', 'Not Started/Future')], default='Open', max_length=20)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', markdownx.models.MarkdownxField(blank=True, null=True)),
            ],
        ),
    ]
