# Generated by Django 3.2.17 on 2023-02-18 12:27

import apps.sprints.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0004_alter_sprint_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end',
            field=models.DateTimeField(blank=True, default=apps.sprints.models.Sprint.default_sprint_end, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='started',
            field=models.DateTimeField(blank=True, default=apps.sprints.models.Sprint.default_sprint_started, null=True),
        ),
    ]
