# Generated by Django 3.2.17 on 2023-02-18 13:55

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0005_auto_20230218_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, default='', null=True),
        ),
    ]
