version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/devlog/web/staticfiles
      - media_volume:/home/devlog/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - ~/.prod_data/devlog_db:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    ports:
        - "6543:5432"
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/devlog/web/staticfiles
      - media_volume:/home/devlog/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  database:
  static_volume:
  media_volume:
